// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteRecord(buf []byte, offset flatbuffers.UOffsetT) *DeleteRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteRecord{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DeleteRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteRecord) Typ() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 4
}

func (rcv *DeleteRecord) MutateTyp(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *DeleteRecord) Id(obj *Id) *Id {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Id)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeleteRecord) OwnerId(obj *Id) *Id {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Id)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeleteRecord) Updated() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteRecord) MutateUpdated(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *DeleteRecord) TransactionId(obj *Id) *Id {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Id)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DeleteRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func DeleteRecordAddTyp(builder *flatbuffers.Builder, typ int8) {
	builder.PrependInt8Slot(0, typ, 4)
}
func DeleteRecordAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(id), 0)
}
func DeleteRecordAddOwnerId(builder *flatbuffers.Builder, ownerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(ownerId), 0)
}
func DeleteRecordAddUpdated(builder *flatbuffers.Builder, updated uint64) {
	builder.PrependUint64Slot(3, updated, 0)
}
func DeleteRecordAddTransactionId(builder *flatbuffers.Builder, transactionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(transactionId), 0)
}
func DeleteRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
