// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Id struct {
	_tab flatbuffers.Table
}

func GetRootAsId(buf []byte, offset flatbuffers.UOffsetT) *Id {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Id{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Id) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Id) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Id) Hex() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IdAddHex(builder *flatbuffers.Builder, hex flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hex), 0)
}
func IdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
