// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OKKeyFieldScoreTxnValues struct {
	_tab flatbuffers.Table
}

func GetRootAsOKKeyFieldScoreTxnValues(buf []byte, offset flatbuffers.UOffsetT) *OKKeyFieldScoreTxnValues {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OKKeyFieldScoreTxnValues{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OKKeyFieldScoreTxnValues) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OKKeyFieldScoreTxnValues) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OKKeyFieldScoreTxnValues) Duration() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OKKeyFieldScoreTxnValues) MutateDuration(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *OKKeyFieldScoreTxnValues) Records(obj *KeyFieldScoreTxnValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OKKeyFieldScoreTxnValues) RecordsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func OKKeyFieldScoreTxnValuesStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OKKeyFieldScoreTxnValuesAddDuration(builder *flatbuffers.Builder, duration int64) {
	builder.PrependInt64Slot(0, duration, 0)
}
func OKKeyFieldScoreTxnValuesAddRecords(builder *flatbuffers.Builder, records flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(records), 0)
}
func OKKeyFieldScoreTxnValuesStartRecordsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func OKKeyFieldScoreTxnValuesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
