// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OKNoContent struct {
	_tab flatbuffers.Table
}

func GetRootAsOKNoContent(buf []byte, offset flatbuffers.UOffsetT) *OKNoContent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OKNoContent{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OKNoContent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OKNoContent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OKNoContent) Duration() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OKNoContent) MutateDuration(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func OKNoContentStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OKNoContentAddDuration(builder *flatbuffers.Builder, duration int64) {
	builder.PrependInt64Slot(0, duration, 0)
}
func OKNoContentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
