// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OKVersion struct {
	_tab flatbuffers.Table
}

func GetRootAsOKVersion(buf []byte, offset flatbuffers.UOffsetT) *OKVersion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OKVersion{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OKVersion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OKVersion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OKVersion) Duration() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OKVersion) MutateDuration(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *OKVersion) Records(obj *Version) *Version {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Version)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func OKVersionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OKVersionAddDuration(builder *flatbuffers.Builder, duration int64) {
	builder.PrependInt64Slot(0, duration, 0)
}
func OKVersionAddRecords(builder *flatbuffers.Builder, records flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(records), 0)
}
func OKVersionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
