// automatically generated by the FlatBuffers compiler, do not modify

package schema

const (
	TypeUnknown = 1
	TypePost = 2
	TypePut = 3
	TypeDelete = 4
	TypeRollback = 5
)

var EnumNamesType = map[int]string{
	TypeUnknown:"Unknown",
	TypePost:"Post",
	TypePut:"Put",
	TypeDelete:"Delete",
	TypeRollback:"Rollback",
}

