// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Version struct {
	_tab flatbuffers.Table
}

func GetRootAsVersion(buf []byte, offset flatbuffers.UOffsetT) *Version {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Version{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Version) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Version) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Version) Version() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func VersionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VersionAddVersion(builder *flatbuffers.Builder, version flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(version), 0)
}
func VersionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
